version: '3'
services:
  threads:
    build:
      context: ./services/threads
    # volumes:
    #   - ./services/threads:/usr/src/app
    environment:
      NODE_ENV: production
      PG_CONNECTION_STRING: postgres://postgres:postgrespassword@host.docker.internal:8432/postgres
      PORT: 4001
    ports: ['4001:4001']
  posts:
    build:
      context: ./services/posts
    # volumes:
    #   - ./services/posts:/usr/src/app
    environment:
      NODE_ENV: production
      PG_CONNECTION_STRING: postgres://postgres:postgrespassword@host.docker.internal:7432/postgres
      PORT: 4002
    ports: ['4002:4002']
  gateway:
    build:
      context: ./services/gateway
    depends_on:
      - threads
      - posts
    environment:
      NODE_ENV: production
      PORT: 4000
    ports: ['4000:4000']
